cities/urls.py
from django.urls import path
from .views import CityCreateView, CityListView
from .views import CityUpdateView, CityDeleteView

app_name = 'cities'

urlpatterns = [
    path('update/<int:pk>/', CityUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', CityDeleteView.as_view(), name='delete'),
    path('add/', CityCreateView.as_view(), name='add'),
    path('', CityListView.as_view(), name='list')
]

trains/urls.py
from django.urls import path
from .views import TrainCreateView, TrainListView
from .views import TrainUpdateView,  TrainDeleteView


app_name = 'trains'

urlpatterns = [
    path('update/<int:pk>/', TrainUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', TrainDeleteView.as_view(), name='delete'),
    path('add/', TrainCreateView.as_view(), name='add'),
    path('', TrainListView.as_view(), name='list'),
]

travel/travel/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

trains/models.py
from django.db import models
from django.core.exceptions import ValidationError
from cities.models import City


class Train(models.Model):
    """Потяг"""
    name = models.CharField(max_length=100, unique=True, verbose_name='Номер потягу')
    from_city = models.ForeignKey(City, on_delete=models.CASCADE,
                                  verbose_name='Звідки', related_name='from_city')
    to_city = models.ForeignKey(City, on_delete=models.CASCADE,
                                verbose_name='Куди', related_name='to_city')
    travel_time = models.IntegerField(verbose_name='Час в дорозі')

    class Meta:
        verbose_name = 'Потяг'
        verbose_name_plural = 'Потяги'
        ordering = ['name']

    def __str__(self):
        return f'Потяг №{self.name} із {self.from_city} в {self.to_city}'

    def clean(self, *args, **kwargs):
        if self.from_city == self.to_city:
            raise ValidationError('Змініть місто прибуття')
        qs = Train.objects.filter(from_city=self.from_city,
                                  to_city=self.to_city,
                                  travel_time=self.travel_time).exclude(pk=self.pk)
        if qs.exists():
            raise ValidationError('Змініть час в дорозі')
        return super(Train, self).clean(*args, **kwargs)

trains/forms.py
from django import forms
from .models import Train
from cities.models import City


class TrainForm(forms.ModelForm):
    """Форма потягу"""
    name = forms.CharField(label='Потяг', widget=forms.TextInput(
                                              attrs={'class': 'form-control',
                                                     'placeholder': 'Введіть номер потягу'}))
    from_city = forms.ModelChoiceField(label='Звідки', queryset=City.objects.all(),
                                       widget=forms.Select(attrs={'class': 'form-control',
                                                                  'placeholder': 'Звідки'}))

    to_city = forms.ModelChoiceField(label='Куди', queryset=City.objects.all(),
                                     widget=forms.Select(attrs={'class': 'form-control',
                                                                'placeholder': 'Куди'}))

    travel_time = forms.IntegerField(label='Час', widget=forms.NumberInput(
        attrs={'class': 'form-control',
               'placeholder': 'Час в дорозі'}))

    class Meta(object):
        model = Train
        fields = ('name', 'from_city', 'to_city', 'travel_time')

trains/views.py
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Train
from .forms import TrainForm


class TrainListView(ListView):
    """Список потягів"""
    queryset = Train.objects.all()
    context_object_name = 'objects_list'
    template_name = 'trains/list.html'
    paginate_by = 5


class TrainCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    """Створення потягу"""
    login_url = '/accounts/login/'
    model = Train
    form_class = TrainForm
    template_name = 'trains/create.html'
    success_url = reverse_lazy('trains:list')
    success_message = 'Потяг створено!'


class TrainUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    """Редагування потягу"""
    login_url = '/accounts/login/'
    model = Train
    form_class = TrainForm
    template_name = 'trains/update.html'
    success_url = reverse_lazy('trains:list')
    success_message = 'Потяг відредаговано!'


class TrainDeleteView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    """Видалення потягу"""
    model = Train
    template_name = 'trains/delete.html'
    success_url = reverse_lazy('trains:list')
    success_message = 'Потяг видалено!'
    login_url = '/accounts/login/'

trains/templates/trains/create.html
{% extends "base.html" %}
{% block title %}Створення потягу {% endblock %}

{% block content %}
    <h1 class="display-4">Створити новий потяг </h1>
    <div class="row">
        <div class="col-md-4 mx-auto">
            <form action="" method="post">{% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="Зберегти">
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <a href="{% url 'trains:list' %}">
                <button type="button" class="btn btn-light">Назад до списку</button>
            </a>
        </div>
    </div>
{% endblock %}

trains/templates/trains/delete.html
{% extends "base.html" %}
{% block title %}Видалення потягу{% endblock %}

{% block content %}
    <h1 class="display-4">Видалити потяг </h1>
    <div class="row">
        <div class="col-md-4 mx-auto">
            <form method="post">{% csrf_token %}
                {{form.as_p}}
                <p>Ви впевнені, що хочете видалити"{{ object }}"?</p>
                <input type="submit" value="Так, видалити">
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <a href="{% url 'trains:list' %}">
                <button type="button" class="btn btn-light">Назад до списку</button>
            </a>
        </div>
    </div>
{% endblock %}

trains/templates/trains/home.html
{% extends 'base.html' %}

{% block title %} Потяги {% endblock title %}

{% block content %}
<h1 class="display-4 text-center my-4">Потяги</h1>
<div class="row ">
<div class='col-md-6 mx-auto'>
<table class="table table-striped">
    <thead>
        <tr>
        <th> Номер потягу</th>
        <th> Звідки</th>
        <th> Куди</th>
        <th> Час в дорозі</th>
        <th> &nbsp;</th>
        <th> &nbsp;</th>
        </tr>
    </thead>
    <tbody>
        {% for object in objects_list %}
        <tr>
            <td>{{object.name}}</td>
            <td>{{object.from_city}}</td>
            <td>{{object.to_city}}</td>
            <td>{{object.travel_time}}</td>
            <td></td>
            <td></td>
            <td> {% if user.is_authenticated %}
                <a href='{% url "trains:update" pk=object.pk%}'>
                    <button type="button" class="btn btn-primary btn-sm">Редагувати</button>
                </a>
                {% endif %}

            </td>
            <td> {% if user.is_authenticated %}
                <a href='{% url "trains:delete" pk=object.pk%}'>
                    <button type="button" class="btn btn-danger btn-sm">Видалити</button>
                </a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
</div>
 <div id="navigation" class="container my-1">
     <div class="row">
         <div class="col-md-8 ml-auto">
             <nav aria-label="Page navigation example">
                 <ul class="pagination ">
                     {% if objects_list.has_previous %}
                        <li class="page-item">
                            <a class="page-link"
                                href="?page={{ objects_list.previous_page_number }}"
                                    aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                            </a>
                        </li>
                     {% endif %}
                     {% for page in objects_list.paginator.page_range %}
                        {% if page == objects_list.number %}
                            <li class="page-item active">
                                <a class="page-link" href="#"> {{page}}
                                    <span class="sr-only">(current)</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link"
                                    href="?page={{page}}">
                                    {{page}}
                                </a>
                            </li>
                        {% endif %}
                     {% endfor %}
                     {% if objects_list.has_next %}
                        <li class="page-item">
                            <a class="page-link"
                                href="?page={{objects_list.paginator.num_pages }}"
                                    aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                     {% endif %}
                 </ul>
             </nav>
         </div>
     </div>
 </div>
<div class="row">
    <div class='col-md-6 ml-auto'>
        <a href='{% url "trains:add" %}'>
        {% if user.is_authenticated %}
            <button type="button" class="btn btn-info btn-sm"> Добавити новий потяг </button>
        </a>
        {% endif %}
    </div>
</div>
{% endblock content %}

trains/templates/trains/list.html
{% extends 'base.html' %}

{% block title %} Потяги {% endblock title %}

{% block content %}
<h1 class="display-4 text-center my-4">Потяги</h1>
<div class="row ">
<div class='col-md-6 mx-auto'>
<table class="table table-striped">
    <thead>
        <tr>
        <th> Номер потягу</th>
        <th> Звідки</th>
        <th> Куди</th>
        <th> Час в дорозі</th>
        <th> &nbsp;</th>
        <th> &nbsp;</th>
        </tr>
    </thead>
    <tbody>
        {% for object in objects_list %}
        <tr>
            <td>{{object.name}}</td>
            <td>{{object.from_city}}</td>
            <td>{{object.to_city}}</td>
            <td>{{object.travel_time}}</td>
            <td></td>
            <td></td>
            <td> {% if user.is_authenticated %}
                <a href='{% url "trains:update" pk=object.pk%}'>
                    <button type="button" class="btn btn-primary btn-sm">Редагувати</button>
                </a>
                {% endif %}

            </td>
            <td> {% if user.is_authenticated %}
                <a href='{% url "trains:delete" pk=object.pk%}'>
                    <button type="button" class="btn btn-danger btn-sm">Видалити</button>
                </a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
</div>
 <div id="navigation" class="container my-1">
     <div class="row">
         <div class="col-md-8 ml-auto">
             <nav aria-label="Page navigation example">
                 <ul class="pagination ">
                     {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link"
                                href="?page={{ page_obj.previous_page_number }}"
                                    aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Наступна</span>
                            </a>
                        </li>
                     {% endif %}
                     {% for page in page_obj.paginator.page_range %}
                        {% if page == page_obj.number %}
                            <li class="page-item active">
                                <a class="page-link" href="#"> {{page}}
                                    <span class="sr-only">(current)</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link"
                                    href="?page={{page}}">
                                    {{page}}
                                </a>
                            </li>
                        {% endif %}
                     {% endfor %}
                     {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link"
                                href="?page={{page_obj.paginator.num_pages }}"
                                    aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Наступна</span>
                            </a>
                        </li>
                     {% endif %}
                 </ul>
             </nav>
         </div>
     </div>
 </div>
<div class="row">
    <div class='col-md-6 ml-auto'>
        <a href='{% url "trains:add" %}'>
        {% if user.is_authenticated %}
            <button type="button" class="btn btn-info btn-sm"> Добавити новий потяг </button>
        </a>
        {% endif %}
    </div>
</div>
{% endblock content %}

trains/templates/trains/update.html
{% extends "base.html" %}
{% block title %}Редагування потягу{% endblock %}

{% block content %}
    <h1 class="display-4">Редагувати потяг</h1>
    <div class="row">
        <div class="col-md-4 mx-auto">
            <form action="" method="post">{% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="Зберегти">
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <a href="{% url 'trains:list' %}">
                <button type="button" class="btn btn-light">Назад до списку</button>
            </a>
        </div>
    </div>
{% endblock %}