cities/urls.py
from django.urls import path
from .views import CityCreateView, CityListView
from .views import CityUpdateView, CityDeleteView

app_name = 'cities'

urlpatterns = [
    path('update/<int:pk>/', CityUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', CityDeleteView.as_view(), name='delete'),
    path('add/', CityCreateView.as_view(), name='add'),
    path('', CityListView.as_view(), name='list')
]

travel/travel/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

cities/models.py
from django.db import models


class City(models.Model):
    """Місто"""
    name = models.CharField(max_length=100, unique=True, verbose_name='Місто')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Місто'
        verbose_name_plural = 'Міста'
        ordering = ['name']

cities/forms.py
from django import forms
from .models import City


class CityForm(forms.ModelForm):
    """Форма населеного пункту"""
    name = forms.CharField(label='Місто', widget=forms.TextInput(
                                              attrs={'class': 'form-control',
                                                     'placeholder': 'Введіть назву міста'}))

    class Meta(object):
        model = City
        fields = ('name',)

cities/views.py
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import City
from .forms import CityForm


class CityListView(ListView):
    """Список населених пунктів"""
    queryset = City.objects.all()
    context_object_name = 'objects_list'
    template_name = 'cities/list.html'
    paginate_by = 5


class CityCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    """Створення міста"""
    model = City
    form_class = CityForm
    template_name = 'cities/create.html'
    success_url = reverse_lazy('cities:list')
    success_message = 'Місто створено!'
    login_url = '/accounts/login/'


class CityUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    """Редагування міста"""
    model = City
    form_class = CityForm
    template_name = 'cities/update.html'
    success_url = reverse_lazy('cities:list')
    success_message = 'Місто відредаговано!'
    login_url = '/accounts/login/'


class CityDeleteView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    """Видалення міста"""
    model = City
    template_name = 'cities/delete.html'
    success_url = reverse_lazy('cities:list')
    success_message = 'Місто видалено!'
    login_url = '/accounts/login/'

cities/templates/cities/create.html
{% extends 'base.html' %}
{% block title %}Створення міста {% endblock %}

{% block content %}
    <h1 class="display-4">Створити нове місто </h1>
    <div class="row">
        <div class="col-md-4 mx-auto">
            <form action="" method="post">{% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="Зберегти">
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <a href="{% url 'cities:list' %}">
                <button type="button" class="btn btn-light">Назад до списку</button>
            </a>
        </div>
    </div>
{% endblock %}

cities/templates/cities/delete.html
{% extends 'base.html' %}
{% block title %}Видалення міста{% endblock %}

{% block content %}
    <h1 class="display-4">Видалити місто</h1>
    <div class="row">
        <div class="col-md-4 mx-auto">
            <form method="post">{% csrf_token %}
                {{form.as_p}}
                <p>Ви впевнені, що хочете видалити "{{ object }}"?</p>
                <input type="submit" value="Так, видалити">
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <a href="{% url 'cities:list' %}">
                <button type="button" class="btn btn-light">Назад до списку</button>
            </a>
        </div>
    </div>
{% endblock %}

cities/templates/cities/home.html
{% extends 'base.html' %}

{% block title %} Міста {% endblock title %}

{% block content %}
<h1 class="display-4 text-center my-4">Міста</h1>
<div class="row ">
<div class='col-md-6 mx-auto'>
<table class="table table-striped">
    <tbody>
        {% for object in objects_list %}
        <tr>
                <td>
                {{object.name}}
                </td>
            <td> {% if user.is_authenticated %}
                <a href='{% url "cities:update" pk=object.pk%}'>
                    <button type="button" class="btn btn-primary btn-sm">Редагувати</button>
                </a>
                {% endif %}

            </td>
            <td> {% if user.is_authenticated %}
                <a href='{% url "cities:delete" pk=object.pk%}'>
                    <button type="button" class="btn btn-danger btn-sm">Видалити</button>
                </a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
</div>
 <div id="navigation" class="container my-1">
     <div class="row">
         <div class="col-md-8 ml-auto">
             <nav aria-label="Page navigation example">
                 <ul class="pagination ">
                     {% if objects_list.has_previous %}
                        <li class="page-item">
                            <a class="page-link"
                                href="?page={{ objects_list.previous_page_number }}"
                                    aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                            </a>
                        </li>
                     {% endif %}
                     {% for page in objects_list.paginator.page_range %}
                        {% if page == objects_list.number %}
                            <li class="page-item active">
                                <a class="page-link" href="#"> {{page}}
                                    <span class="sr-only">(current)</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link"
                                    href="?page={{page}}">
                                    {{page}}
                                </a>
                            </li>
                        {% endif %}
                     {% endfor %}
                     {% if objects_list.has_next %}
                        <li class="page-item">
                            <a class="page-link"
                                href="?page={{objects_list.paginator.num_pages }}"
                                    aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                     {% endif %}
                 </ul>
             </nav>
         </div>
     </div>
 </div>
<div class="row">
    <div class='col-md-6 ml-auto'>
        <a href='{% url "cities:add" %}'>
        {% if user.is_authenticated %}
            <button type="button" class="btn btn-info btn-sm"> Добавити нове місто </button>
        </a>
        {% endif %}
    </div>
</div>
{% endblock content %}

cities/templates/cities/list.html
{% extends 'base.html' %}

{% block title %} Міста {% endblock title %}

{% block content %}
<h1 class="display-4 text-center my-4">Міста</h1>
<div class="row ">
<div class='col-md-6 mx-auto'>
<table class="table table-striped">
    <tbody>
        {% for object in objects_list %}
        <tr>
                <td>
                {{object.name}}
                </td>
            <td> {% if user.is_authenticated %}
                <a href='{% url "cities:update" pk=object.pk%}'>
                    <button type="button" class="btn btn-primary btn-sm">Редагувати</button>
                </a>
                {% endif %}

            </td>
            <td> {% if user.is_authenticated %}
                <a href='{% url "cities:delete" pk=object.pk%}'>
                    <button type="button" class="btn btn-danger btn-sm">Видалити</button>
                </a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
</div>
 <div id="navigation" class="container my-1">
     <div class="row">
         <div class="col-md-8 ml-auto">
             <nav aria-label="Page navigation example">
                 <ul class="pagination ">
                     {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link"
                                href="?page={{ page_obj.previous_page_number }}"
                                    aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Попередня</span>
                            </a>
                        </li>
                     {% endif %}
                     {% for page in page_obj.paginator.page_range %}
                        {% if page == page_obj.number %}
                            <li class="page-item active">
                                <a class="page-link" href="#"> {{page}} <span class="sr-only">(current)</span></a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{page}}">{{page}}</a>
                            </li>
                        {% endif %}
                     {% endfor %}
                     {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link"
                                href="?page={{ page_obj.paginator.num_pages }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Наступна</span>
                            </a>
                        </li>
                     {% endif %}
                 </ul>
             </nav>
         </div>
     </div>
 </div>
<div class="row">
    <div class='col-md-6 ml-auto'>
        <a href='{% url "cities:add" %}'>
        {% if user.is_authenticated %}
            <button type="button" class="btn btn-info btn-sm"> Добавити нове місто </button>
        </a>
        {% endif %}
    </div>
</div>
{% endblock content %}

cities/templates/cities/update.html
{% extends 'base.html' %}
{% block title %}Редагування міста{% endblock %}

{% block content %}
    <h1 class="display-4">Редагувати місто</h1>
    <div class="row">
        <div class="col-md-4 mx-auto">
            <form action="" method="post">{% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="Зберегти">
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <a href="{% url 'cities:list' %}">
                <button type="button" class="btn btn-light">Назад до списку</button>
            </a>
        </div>
    </div>
{% endblock %}