accounts/urls.py
from django.urls import path

from .views import login_view, logout_view, register_view

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
]

cities/urls.py
from django.urls import path
from .views import CityCreateView, CityListView
from .views import CityUpdateView, CityDeleteView

app_name = 'cities'

urlpatterns = [
    path('update/<int:pk>/', CityUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', CityDeleteView.as_view(), name='delete'),
    path('add/', CityCreateView.as_view(), name='add'),
    path('', CityListView.as_view(), name='list')
]

trains/urls.py
from django.urls import path
from .views import TrainCreateView, TrainListView
from .views import TrainUpdateView,  TrainDeleteView


app_name = 'trains'

urlpatterns = [
    path('update/<int:pk>/', TrainUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', TrainDeleteView.as_view(), name='delete'),
    path('add/', TrainCreateView.as_view(), name='add'),
    path('', TrainListView.as_view(), name='list'),
]

travel/travel/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

templates/base.html
<!doctype html>
{% load static %}

<!-- Для динамічних ссилок -->
{% url 'home' as home_url %}
{% url 'cities:list' as cities_list_url %}
{% url 'trains:list' as train_list_url %}
{% url 'list' as list_url %}
{% url 'trains:add' as train_add_url %}
{% url 'cities:add' as city_add_url %}

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="{% static 'favicon.ico' %} ">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %} ">

    <title>{% block title %} {% endblock title %}</title>
  </head>
  <body>
  <div class="container">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'home' %}"id="brand">Путівник by Vadym Pashynskyi</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item {% if request.path == home_url %}active{% endif %}">
          <a class="nav-link" href="{% url 'home' %} ">Пошук маршруту</a>
        </li>
        <li class="nav-item {% if request.path == cities_list_url %}active{% endif %}">
          <a class="nav-link" href="{% url 'cities:list' %} ">Міста</a>
        </li>
        <li class="nav-item {% if request.path == train_list_url %} active {% endif %}">
          <a class="nav-link" href="{% url 'trains:list'%}">Потяги</a>
        </li>
        <li class="nav-item {% if request.path == list_url %}active{% endif %}">
          <a class="nav-link" href="{% url 'list' %} ">Маршрути</a>
        </li>
         {% if user.is_authenticated %}
        <li class="nav-item dropdown
        {% if request.path == train_add_url or request.path == city_add_url %}
          active
          {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false"> Добавити </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'cities:add'%}">Нове місто</a>
          <a class="dropdown-item" href="{% url 'trains:add'%}">Новий потяг</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item ">
          <a class="nav-link disabled" href="">Добавити</a>
        </li>
        {% endif %}
        {% if user.is_authenticated %}
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'accounts:logout'%} ">Вийти</a>
          </li>
          {% else %}
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'accounts:login'%} ">Увійти</a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'accounts:register'%} ">Реєстрація</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  </div>
  <div class="container my-4">
    <div class="row">
      <div class="col-md-8 mx-auto">
        {% if messages %}
          {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
              <div class="alert alert-danger messages">
                <span {% if message.tags %} class="{{ message.tags }}"{% endif %}>Увага! {{ message }}</span>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {%else %}
              <div class="alert alert-success messages">
                <span {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% endif %}
          {% endfor %}
        {% endif %}
      </div>
    </div>
  </div>
  <div class="container">
    {% block content %} {% endblock content %}
  </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script>
      $(document).ready(function() {
        $('.js-example-basic-single').select2();
        $(".js-example-basic-multiple").select2();
      });
    </script>

  </body>
</html>